# Packages

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Datasets

In [5]:
df_events = pd.read_csv("../data/events.csv")
df_products = pd.read_csv("../data/products.csv")

# Understanding Events

## Show Events

### Events Schema

In [7]:
df_events.dtypes

user_id       str
product_id    str
event_type    str
timestamp     str
dtype: object

### Events Sample

In [12]:
df_events.head()

  user_id product_id   event_type            timestamp
0  u_0231      p_042         view  2026-01-01 00:09:00
1  u_0078      p_012        click  2026-01-01 00:09:00
2  u_0078      p_012         view  2026-01-01 00:19:00
3  u_0322      p_059  add_to_cart  2026-01-01 00:28:00
4  u_0121      p_045  add_to_cart  2026-01-01 00:37:00

# Understanding Products

## Show Products

### Products Schema

In [8]:
df_products.dtypes

product_id              str
category                str
price               float64
avg_rating          float64
popularity_score    float64
dtype: object

### Products Sample

In [10]:
df_products.head()

  product_id category   price  avg_rating  popularity_score
0      p_000  esporte  115.19         3.1             0.652
1      p_001   livros  406.24         4.3             0.162
2      p_002   beleza   46.82         3.6             0.069
3      p_003   livros  729.27         4.0             0.077
4      p_004   livros  221.85         4.8             0.174